# Generated by Django 3.2.25 on 2025-06-12 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        ('user', '0002_alter_user_prof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='friend.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
