# Generated by Django 3.2.25 on 2026-01-06 13:09

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to=blog.models.blog_content_image_file_path)),
            ],
        ),
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogContentImages',
        ),
    ]
