# Generated by Django 3.2.25 on 2026-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20260106_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
