# Generated by Django 3.2.25 on 2026-01-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='created_at',
        ),
    ]
