# Generated by Django 3.2.25 on 2026-01-07 07:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_date_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to=blog.models.blog_thumbnail_image_file_path),
        ),
    ]
